baseurl: 'https://savemarsdenpoint.com'
title: Save Our Refinery
theme: hugo-theme-cleanwhite
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
preserveTaxonomyNames: true
paginate: 5
hasCJKLanguage: true
outputs:
  home:
    - HTML
    - RSS
    - Algolia
params:
  header_image: img/home-bg-jeep.jpg
  SEOTitle: Convoy 2022 | Save Marsden Point
  description: '赵化冰，程序员, 开源爱好者，生活探险家 | 这里是 赵化冰 的博客，与你一起发现更大的世界。'
  keyword: >-
    Sovereigny, Refinery, Globalism, Klaus Schwab, Energy, Independence, Jabcinda
  slogan: 路在脚下，心向远方
  image_404: img/404-bg.jpg
  title_404: '你来到了没有知识的荒原 :('
  page_view_conter: false
  leancloud_app_id: ''
  leancloud_app_key: ''
  algolia_search: true
  algolia_appId: ''
  algolia_indexName: ''
  algolia_apiKey: ''
  sidebar_about_description: 'Convoy 2022 - '
  sidebar_avatar: img/zhaohuabing.png
  featured_tags: true
  featured_condition_size: 1
  ba_track_id: ''
  disqus_proxy: ''
  disqus_site: ''
  reward: true
  friends: true
  bookmarks: false
  about_me: true
  highlightjs: docco
  social:
    rss: true
    email: youremail@gmail.com
    linkedin: 'https://www.linkedin.com/in/yourlinkedinid'
    stackoverflow: 'https://stackoverflow.com/users/yourstackoverflowid'
    github: 'https://github.com/yourgithub'
    wechat: your wechat qr code image
  friend_link:
    - title: Linda的博客
      href: 'https://zhaozhihan.com'
  bookmark_link:
    - title: Martin Fowler
      href: 'https://martinfowler.com'
    - title: ServiceMesher
      href: 'http://www.servicemesher.com'
    - title: Pxhere
      href: 'https://pxhere.com'
    - title: unsplash
      href: 'https://unsplash.com'
  addtional_menus:
    - title: BOOKS
      href: /top/books/
    - title: ABOUT
      href: /top/about/
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
    params:
      - categories
      - tags
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
