baseURL: https://savemarsdenpoint.com
languageCode: en-us
defaultContentLanguage: en
title: Save Marsden Point
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: false
taxonomies:
  tag: tags
permalinks:
  post: /:filename/
imaging:
  quality: 99
params:
  description: Notes on the value of the Marsden Point Oil Refinery to New Zealand by [Dig In At Marsden](https://www.securemarsdenrefinery.nz/)
  homeMetaContent: Notes on the value of the Marsden Point Oil Refinery to New Zealand by [Dig In At Marsden Point](https://www.securemarsdenrefinery.nz/)
  footer: By [Dig In At Marsden](https://www.securemarsdenrefinery.nz)
  # dateFormat: Jan 2, 2006
  hideHeaderLinks: false
  search: false
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: true
  navTitleText: Save Marsden Point
  logoAlt: An alternative text description of the logo
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js
menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Impact of Impact Only
      url: /report-import-only-impact
      weight: 3
    - name: Environment
      url: /environment
      weight: 3
    - name: Timeline
      url: /timeline/
      weight: 3
    - name: In The Preess
      url: /in-the-press/
      weight: 3
    - name: NZ Energy Market
      url: /nz-energy-market
      weight: 3
    - name: Refinery Operation
      url: /refinery-operation
      weight: 3
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
