---
site: blogdown:::blogdown_site
---

- https://www.stuff.co.nz/business/127998986/marsden-pt-refinery-should-not-be-taking-its-last-crude-oil-shipment-workers-say
- [Refinery ripe for investment](https://www.rnz.co.nz/news/business/463048/refining-nz-ripe-for-investors-when-it-transitions-to-channel-infrastructure-report)
- [Refinery ripe for investment](https://www.rnz.co.nz/news/business/463048/refining-nz-ripe-for-investors-when-it-transitions-to-channel-infrastructure-report)
- [Refinery ripe for investment](https://www.rnz.co.nz/news/business/463048/refining-nz-ripe-for-investors-when-it-transitions-to-channel-infrastructure-report)


- [](https://channelnz.com/investor-centre/reports-presentations/)
- [](https://businessdesk.co.nz/article/marsden-point-oil-refinery-confirms-shutdown-after-six-decades)
- [Namoi James April 8 2022](https://www.newsroom.co.nz/pro/pro-talks-naomi-james-offers-marsden-point-oil-tanks-for-national-security-fuel-reserve)

- [MBIE Fuel Supply Resilience without a domestic refinery](https://www.mbie.govt.nz/dmsdocument/17733-fuel-supply-resilience-without-a-domestic-oil-refinery-proactiverelease-pdf]
- https://www.haletwomey.co.nz/
- [REFINING NZ IMPACT OF CONVERSION TO FUELS TERMINAL](https://www.mbie.govt.nz/dmsdocument/15260-refining-nz-impact-of-conversion-to-fuels-terminal)

- (https://www.mbie.govt.nz/building-and-energy/energy-and-natural-resources/energy-statistics-and-modelling/energy-statistics/oil-statistics/)

[Wiki Oil and Gas in NZ]((https://en.wikipedia.org/wiki/Oil_and_gas_industry_in_New_Zealand)
https://www.energyresources.org.nz/
https://www.engineeringnz.org/programmes/heritage/heritage-records/marsden-point-oil-refinery/
https://fuelquality.tradingstandards.govt.nz/for-consumers/the-fuel-industry-in-new-zealand/
https://www.worldometers.info/oil/new-zealand-oil/
https://www.newsroom.co.nz/russia-ukraine-war-changes-fundamentals-on-nz-fuel-supplies
https://www.rnz.co.nz/news/business/457607/fuel-experts-divided-on-impact-of-marsden-point-refinery-closure
https://www.rnz.co.nz/news/national/443869/marsden-point-closure-could-expose-nz-to-fuel-security-risks-report-says
https://www.stuff.co.nz/business/126002293/marsden-point-refinery-closure-threatens-energy-security-maritime-union-says
https://fyi.org.nz/request/15722-copies-of-consultants-reports-and-communications-between-mbie-and-stakeholders-related-to-the-potential-closure-of-marsden-point-oil-refinery
https://www.jasmax.com/people/sjoerd-post/
https://www.haletwomey.co.nz/
https://www.mbie.govt.nz/dmsdocument/12087-refining-nz-accelerating-renewable-energy-and-energy-efficiency-submission-pdf

https://www.newsroom.co.nz/marsden-point-refinery-closure-to-save-100mt-co2
https://www.stuff.co.nz/business/127998986/marsden-pt-refinery-should-not-be-taking-its-last-crude-oil-shipment-workers-say




There is zero impact on atmospheric CO2 concemtration from rrefining offshore.
We substitute the crack spread for physical cracking here in NZ

- Raise awareness to make the closure of Marsden Point politically toxic. 

- Concerned about the lack of competence of the government.


By converting to an import terminal, James said the company would help New Zealand meet its decarbonisation targets and 2030 commitments. She said Marsden Point’s scope 1 and 2 emissions would be reduced by 98 percent – equivalent to almost 1 million tonnes of carbon dioxide a year.

In addition, the company would significantly reduce its electricity use, and would no longer need to use any gas – reducing the company’s exposure to electricity and gas costs and demand on these constrained markets.

