baseurl: 'https://savemarsdenpoint.com'
title: Save Marsden Point
theme: hugo-theme-cleanwhite
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
preserveTaxonomyNames: true
paginate: 5
hasCJKLanguage: true
outputs:
  home:
    - HTML
    - RSS
    - Algolia
params:
  header_image: img/marsden-sunset.png
  SEOTitle: Convoy 2022 | Save Marsden Point
  description: Description here
  keyword: >-
    Sovereigny, Refinery, Globalism, Klaus Schwab, Energy, Independence, Jabcinda
  slogan: An Economic Insurance Policy for New Zealand
  image_404: img/404-bg.jpg
  title_404: 'Not found'
  page_view_conter: false
  leancloud_app_id: ''
  leancloud_app_key: ''
  algolia_search: true
  algolia_appId: ''
  algolia_indexName: ''
  algolia_apiKey: ''
  sidebar_about_description: Convoy 2022
  sidebar_avatar: img/favicon.png
  featured_tags: true
  featured_condition_size: 1
  ba_track_id: ''
  disqus_proxy: ''
  disqus_site: ''
  reward: true
  friends: true
  bookmarks: false
  about_me: true
  highlightjs: docco
  social:
    rss: true
    stackoverflow: 'https://stackoverflow.com/users/yourstackoverflowid'
    wechat: your wechat qr code image
  friend_link:
    - title: Daily Telegraph
      href: https://dailytelegraph.co.nz
    - title: Social Credit
      href: https://www.socialcredit.nz/refineryinfo
    - title: Democracy NZ
      href: https://democracynz.org
  addtional_menus:
    - title: ABOUT
      href: /top/about/
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
    params:
      - categories
      - tags
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
